### ISSUE TITLE
Path issues with file stored in extensions folder

### ISSUE THREAD

**Issue by cderv** [mcanouil/quarto-revealjs-coeos#4]
When the extension is installed locally, there will be a namespace folder added in the path
````
test-reveal/
+-- test-reveal.qmd
\-- _extensions
    \-- mcanouil
        \-- coeos
            +-- about.qmd
            +-- coeos.scss
            +-- coeos.svg
            +-- favicon.html
            +-- LICENSE
            +-- setup-ggplot2-coeos.R
            \-- _extension.yml
````

This means that the path in `template.qmd` that refer to resource inside the extension folder are not correct without adding `mcanouil`. 

Using https://quarto.org/docs/extensions/formats.html#format-resources those resources could be copied in the root folder if needed, otherwise they need to contain the namespace key 

It prevents the template to work on my side after doing
````powershell
quarto use template mcanouil/quarto-revealjs-coeos
````

Is this working for you ?

**Comment by mcanouil** [comment]
I was using the extension mechanism, mostly because with `quarto use template mcanouil/quarto-revealjs-coeos` creating a directory is mandatory.
We can't use it within a directory, such as an open workspace in VSCode.

I am checking with the `use template` now.

**Comment by mcanouil** [comment]
@cderv Hum, I do not understand how the `format-resources` is supposed to work ...
The directory tree structure should be added to the documentation to make it clear what is relative to what.

**Comment by cderv** [comment]
> I am checking with the use template now.

`quarto use template` will install the extension and gets the template QMD file, like with R Markdown template

`quarto install extension` will just install the extension without getting the template.qmd to the user. 

That is the difference between both; See https://quarto.org/docs/extensions/formats.html#distributing-formats

If you prefer the second way that is fine, but know some user can still do the first way and the `template.qmd` is supposed to be working

**Comment by mcanouil** [comment]
I get the idea, this is why, I switched not properly to the `use template` approach.

**Comment by cderv** [comment]
Ok that is fine. But `quarto use extension` was not correct hence the PR I made. 

Just know that user will more use `quarto use` to get the template that usually contains some explanation and stuff. Like with R Markdown.

**Comment by mcanouil** [comment]
> @cderv Hum, I do not understand how the `format-resources` is supposed to work ... The directory tree structure should be added to the documentation to make it clear what is relative to what.

I added the `format-resources` lines but this does not solve the use of relative (to root) as I understood what it is for, e.g., `{{< include about.qmd >}}` or `source("setup-ggplot2-coeos.R")`

**Comment by cderv** [comment]
> I do not understand how the format-resources is supposed to work ...

It is relative to the extension directory, and paths will be resolved for copy by Quarto. 
You could suggest some improvement in the doc in `quarto-dev/quarto-web` repo in an issue.

**Comment by cderv** [comment]
Let me check that then

**Comment by mcanouil** [comment]
I don't know if it's a bug or me 😅

I can see from https://github.com/quarto-journals/jss that with format-resources the `jsslogo.jpg`get copied to root make it usable with for example `![](jsslogo.jpg)` in the quarto document.

Now, I believe I set the `_extension.yml` right (https://github.com/mcanouil/quarto-revealjs-coeos/blob/main/_extensions/coeos/_extension.yml) but https://github.com/mcanouil/quarto-revealjs-coeos/blob/main/template.qmd does not work `source("setup-ggplot2-coeos.R")` and `{{< include about.qmd >}}` produce "not found" errors.

Did I miss something?

**Comment by mcanouil** [comment]
It's definitely a bug, resources are not copied for HTML formats.
it only works for PDF.

**Comment by mcanouil** [comment]
I tweaked my CI to install, build, and publish the extension, for now using full "install" path to get the resources.

https://github.com/mcanouil/quarto-revealjs-coeos/blob/main/.github/workflows/publish.yml

Note: I am going to create a GHA based on the one above designed to work for quarto templates (readme with example link, preview images, etc.)

**Comment by mcanouil** [comment]
Wait for 1.1 release https://github.com/quarto-dev/quarto-cli/issues/1538
